spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:5432/smart_home
    username: postgres
    password: postgres
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql

server:
  port: 8082

app:
  kafka:
    host: ${KAFKA_HOST:localhost}
    port: ${KAFKA_PORT:9092}
