apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: write-user
rules:
- apiGroups: [""]
  resources: ["pods, deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch"] 