apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-cluster-admin-user3
subjects:
- kind: User
  name: user3
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system-cluster-admin
  apiGroup: rbac.authorization.k8s.io