apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: scaletestapp
  template:
    metadata:
      labels:
        run: scaletestapp
    spec:
      containers:
      - name: scaletestapp
        image: shestera/scaletestapp
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: "20Mi"
          requests:
            cpu: 200m
            memory: "3Mi"